(assert
 (= "xx" (scat "xx" ""))
 (= "xx" (scat "x" "x"))
 (= "xx" (scat "" "xx"))
 (= 4 (slen "slen"))
 (= "bidden" (ssub "forbidden planet" 3 9))
 (= "all of it" (ssub "all of it" -9 100))
 )

(: (stripPrefix p s) (? (= p (ssub s 0 (slen p))) (ssub s (slen p) (slen s))))
(assert (= "eon" (stripPrefix "vapor" "vaporeon")))
(: (lit l y n s) ((\ ss (? ss (y ss (X l 0)) (n s))) (stripPrefix l s))
   (drop p y) (p (\ s _ (y s 0)))
   (opt p y _) (p y (\ s (y s 0)))
   (cat a b y n) (a (\ s l (b (\ s m (y s (append l m))) n s)) n)
   (alt a b y n) (a y (b y n))
   (rep a y n s) ((opt (cat a (rep a))) y n s))
(assert
 (= '("eon" "vapor")
  (lit "vapor" X 0 "vaporeon"))
 (= '("rrq" "R")
  (alt (lit "r") (lit "R") X 0 "Rrrq"))
 (= '("q" "R" "r" "r")
  (rep (alt (lit "r") (lit "R")) X 0 "Rrrq")))
