(putc 10)
(. (test-get 'count)) (puts " tests in ")
(: ms (- (clock ()) test_t0)
   s  (/ ms 1000)
   us (% ms 1000)
   p (? (< us 10) ".00" (< us 100) ".0" ".")
   (, (. s) (puts p) (puts(. us) (puts " seconds") (putc 10))))
(: f (test-get 'fail) (? f (,
 (. (llen f)) (puts " failed:") (putc 10)
 (each f (\ x (, (puts "  ") (.. x))))
)))
