// kinds.h -- GENERATED by tools/mx.l. do not edit; edit the table there.
// the TWO rosters. `enum q` is the dispatch lattice: the order love.h's
// narrative reads, and the row and column index of the +/* matrices in mx.h.
// `enum d` is what a heap object's hot SAYS it is -- the nine ai_typ can
// answer, so a switch over it is exhaustive and needs no default -- and so it
// carries no count, which would be a case with no value. KN is enum q's own
// length; mx.h's ai_kind_of_d is the crossing between the two.
// doc/clay.md rung 2b; the drift check is `make test_clay`.
enum q { KMint, KNom, KCharm, KSun, KGem, KTwin, KBig, KTrayZ, KTrayR, KTrayC, KTrayO, KString, KChain, KTablet, KHot, KN };
enum d { DMint, DNom, DSun, DGem, DTwin, DBig, DTray, DString, DChain };
