// kinds.h -- GENERATED by tools/mx.l. do not edit; edit the table there.
//
enum q { KMint, KNom, KCharm, KSun, KGem, KTwin, KBig, KTrayZ, KTrayR, KTrayC, KTrayO, KString, KChain, KTablet, KHot, KN };
enum d { DMint, DNom, DSun, DGem, DTwin, DBig, DTray, DString, DChain };
