// kinds.h -- GENERATED by tools/mx.l. do not edit; edit the table there.
// the kind lattice: the dispatch order love.h's narrative reads, and the row
// and column index of the +/* matrices in mx.h -- ONE roster, so the enum and
// the grid it dimensions cannot drift apart. KN is the count, not a kind.
// doc/clay.md rung 2b; the drift check is `make test_clay`.
enum q { KMint, KNom, KCharm, KWide, KFlo, KCplx, KBig, KVec, KArrZ, KArrR, KArrC, KArrO, KString, KChain, KMap, KHot, KN };
