(: (f m n) 
    (: m+ (+ m) n+ (+ n)
              (g a) (? (< a 0) a (h (n+ a)))
              (h a) (? (< a 0) a (g (m+ a)))
              h)
   f3 (f -3)
   f37 (f3 -7)
 (,
    (assert (= -1 (f37 99)))
    (assert (= -7 (f37 33)))))
