(: t (tnew .)
   (Put k v) (set k v t)
   Del (tdel 0 t)
   Get (tget 0 t)
 (, (Put 1 2)
    (Put 2 3)
    (Put 3 4)
    (Put 't 'f)
    (assert
     (= 4 (len t))
     (= 4 (len (tkeys t))))
    (Del 2)
    (Del 't)
    (assert
     (= 2 (len t))
     (= 2 (len (tkeys t))))
    (: (table-to-list t) (foldl 0 (\ l k (X k (X (Get k) l))) (tkeys t))
     (assert (= (* 2 (len t)) (len (table-to-list t)))))))
