(* proof/rocq/mx.v -- GENERATED by tools/mx2coq.l from THE TABLE, tools/mx.l --
   the same love datum love.c's mx.h is laid from, so the theorem and the code
   are two derivations of one source and cannot drift (doc/clay.md rung 2).
   Do not edit; regenerate with `make test_mx`.

   The +/* dispatch matrices, their SHAPE machine-checked -- what the narrative
   states as prose: every kind collapses to a BAND (the partition is derived
   from the table by row+column equality, both ops at once), the 225-
   cell tables factor through the band quotient with nothing left over, the
   dispatch COMMUTES (orientation lives in the lane fn, never the table), and
   the diagonal reads the lattice: one lane per band, the algebra ladder.
   KMint is its own band, the unit lane whole: the dispatchers early-out a
   bare mint as the UNIT before indexing (the fast path), and the matrix says
   the same thing (lvm_bin_unit), so nothing rests on the early-out and the
   theorems close by vm_compute over the WHOLE square. *)
From Stdlib Require Import List Arith.
Import ListNotations.

Inductive kind := KMint | KNom | KCharm | KSun | KGem | KTwin | KBig | KTrayZ | KTrayR | KTrayC | KTrayO | KString | KChain | KTablet | KHot.
Inductive lane := Lbin_unit | Ladd_string | Ladd_seq | Laddh | Laddn | L0 | Lmul_rep | Lmulh | Lmuln | Lmul_cart.
Definition lane_eqb (x y : lane) : bool := match x, y with Lbin_unit, Lbin_unit => true | Ladd_string, Ladd_string => true | Ladd_seq, Ladd_seq => true | Laddh, Laddh => true | Laddn, Laddn => true | L0, L0 => true | Lmul_rep, Lmul_rep => true | Lmulh, Lmulh => true | Lmuln, Lmuln => true | Lmul_cart, Lmul_cart => true | _, _ => false end.

Definition addmx (a b : kind) : lane :=
 match a with
 | KMint => match b with KMint => Lbin_unit | KNom => Lbin_unit | KCharm => Lbin_unit | KSun => Lbin_unit | KGem => Lbin_unit | KTwin => Lbin_unit | KBig => Lbin_unit | KTrayZ => Lbin_unit | KTrayR => Lbin_unit | KTrayC => Lbin_unit | KTrayO => Lbin_unit | KString => Lbin_unit | KChain => Lbin_unit | KTablet => Lbin_unit | KHot => Lbin_unit end
 | KNom => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Ladd_string | KSun => Ladd_string | KGem => Ladd_string | KTwin => Ladd_string | KBig => Ladd_string | KTrayZ => Ladd_string | KTrayR => Ladd_string | KTrayC => Ladd_string | KTrayO => Ladd_string | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KCharm => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KSun => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KGem => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KTwin => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KBig => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KTrayZ => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KTrayR => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KTrayC => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KTrayO => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Laddn | KSun => Laddn | KGem => Laddn | KTwin => Laddn | KBig => Laddn | KTrayZ => Laddn | KTrayR => Laddn | KTrayC => Laddn | KTrayO => Laddn | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KString => match b with KMint => Lbin_unit | KNom => Ladd_string | KCharm => Ladd_string | KSun => Ladd_string | KGem => Ladd_string | KTwin => Ladd_string | KBig => Ladd_string | KTrayZ => Ladd_string | KTrayR => Ladd_string | KTrayC => Ladd_string | KTrayO => Ladd_string | KString => Ladd_string | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KChain => match b with KMint => Lbin_unit | KNom => Ladd_seq | KCharm => Ladd_seq | KSun => Ladd_seq | KGem => Ladd_seq | KTwin => Ladd_seq | KBig => Ladd_seq | KTrayZ => Ladd_seq | KTrayR => Ladd_seq | KTrayC => Ladd_seq | KTrayO => Ladd_seq | KString => Ladd_seq | KChain => Ladd_seq | KTablet => Laddh | KHot => Laddh end
 | KTablet => match b with KMint => Lbin_unit | KNom => Laddh | KCharm => Laddh | KSun => Laddh | KGem => Laddh | KTwin => Laddh | KBig => Laddh | KTrayZ => Laddh | KTrayR => Laddh | KTrayC => Laddh | KTrayO => Laddh | KString => Laddh | KChain => Laddh | KTablet => Laddh | KHot => Laddh end
 | KHot => match b with KMint => Lbin_unit | KNom => Laddh | KCharm => Laddh | KSun => Laddh | KGem => Laddh | KTwin => Laddh | KBig => Laddh | KTrayZ => Laddh | KTrayR => Laddh | KTrayC => Laddh | KTrayO => Laddh | KString => Laddh | KChain => Laddh | KTablet => Laddh | KHot => Laddh end
 end.
Definition mulmx (a b : kind) : lane :=
 match a with
 | KMint => match b with KMint => Lbin_unit | KNom => Lbin_unit | KCharm => Lbin_unit | KSun => Lbin_unit | KGem => Lbin_unit | KTwin => Lbin_unit | KBig => Lbin_unit | KTrayZ => Lbin_unit | KTrayR => Lbin_unit | KTrayC => Lbin_unit | KTrayO => Lbin_unit | KString => Lbin_unit | KChain => Lbin_unit | KTablet => Lbin_unit | KHot => Lbin_unit end
 | KNom => match b with KMint => Lbin_unit | KNom => L0 | KCharm => Lmul_rep | KSun => Lmul_rep | KGem => Lmul_rep | KTwin => Lmul_rep | KBig => Lmul_rep | KTrayZ => Lmul_rep | KTrayR => Lmul_rep | KTrayC => Lmul_rep | KTrayO => Lmul_rep | KString => L0 | KChain => L0 | KTablet => Lmulh | KHot => Lmulh end
 | KCharm => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KSun => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KGem => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KTwin => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KBig => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KTrayZ => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KTrayR => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KTrayC => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KTrayO => match b with KMint => Lbin_unit | KNom => Lmul_rep | KCharm => Lmuln | KSun => Lmuln | KGem => Lmuln | KTwin => Lmuln | KBig => Lmuln | KTrayZ => Lmuln | KTrayR => Lmuln | KTrayC => Lmuln | KTrayO => Lmuln | KString => Lmul_rep | KChain => Lmul_rep | KTablet => Lmulh | KHot => Lmulh end
 | KString => match b with KMint => Lbin_unit | KNom => L0 | KCharm => Lmul_rep | KSun => Lmul_rep | KGem => Lmul_rep | KTwin => Lmul_rep | KBig => Lmul_rep | KTrayZ => Lmul_rep | KTrayR => Lmul_rep | KTrayC => Lmul_rep | KTrayO => Lmul_rep | KString => L0 | KChain => L0 | KTablet => Lmulh | KHot => Lmulh end
 | KChain => match b with KMint => Lbin_unit | KNom => L0 | KCharm => Lmul_rep | KSun => Lmul_rep | KGem => Lmul_rep | KTwin => Lmul_rep | KBig => Lmul_rep | KTrayZ => Lmul_rep | KTrayR => Lmul_rep | KTrayC => Lmul_rep | KTrayO => Lmul_rep | KString => L0 | KChain => Lmul_cart | KTablet => Lmulh | KHot => Lmulh end
 | KTablet => match b with KMint => Lbin_unit | KNom => Lmulh | KCharm => Lmulh | KSun => Lmulh | KGem => Lmulh | KTwin => Lmulh | KBig => Lmulh | KTrayZ => Lmulh | KTrayR => Lmulh | KTrayC => Lmulh | KTrayO => Lmulh | KString => Lmulh | KChain => Lmulh | KTablet => Lmulh | KHot => Lmulh end
 | KHot => match b with KMint => Lbin_unit | KNom => Lmulh | KCharm => Lmulh | KSun => Lmulh | KGem => Lmulh | KTwin => Lmulh | KBig => Lmulh | KTrayZ => Lmulh | KTrayR => Lmulh | KTrayC => Lmulh | KTrayO => Lmulh | KString => Lmulh | KChain => Lmulh | KTablet => Lmulh | KHot => Lmulh end
 end.
Definition band (k : kind) : nat := match k with KMint => 0 | KNom | KString => 1 | KCharm | KSun | KGem | KTwin | KBig | KTrayZ | KTrayR | KTrayC | KTrayO => 2 | KChain => 3 | KTablet | KHot => 4 end.
Definition rk : list kind := [KMint; KNom; KCharm; KSun; KGem; KTwin; KBig; KTrayZ; KTrayR; KTrayC; KTrayO; KString; KChain; KTablet; KHot].

Definition addb : list (list lane) := [
  [Lbin_unit; Lbin_unit; Lbin_unit; Lbin_unit; Lbin_unit];
  [Lbin_unit; Ladd_string; Ladd_string; Ladd_seq; Laddh];
  [Lbin_unit; Ladd_string; Laddn; Ladd_seq; Laddh];
  [Lbin_unit; Ladd_seq; Ladd_seq; Ladd_seq; Laddh];
  [Lbin_unit; Laddh; Laddh; Laddh; Laddh]
 ].
Definition mulb : list (list lane) := [
  [Lbin_unit; Lbin_unit; Lbin_unit; Lbin_unit; Lbin_unit];
  [Lbin_unit; L0; Lmul_rep; L0; Lmulh];
  [Lbin_unit; Lmul_rep; Lmuln; Lmul_rep; Lmulh];
  [Lbin_unit; L0; Lmul_rep; Lmul_cart; Lmulh];
  [Lbin_unit; Lmulh; Lmulh; Lmulh; Lmulh]
 ].
Definition addband (x y : nat) : lane := nth y (nth x addb []) Lbin_unit.
Definition mulband (x y : nat) : lane := nth y (nth x mulb []) Lbin_unit.

Theorem add_factors_through_bands : forallb (fun a => forallb (fun b => lane_eqb (addmx a b) (addband (band a) (band b))) rk) rk = true.
Proof. vm_compute. reflexivity. Qed.
Theorem mul_factors_through_bands : forallb (fun a => forallb (fun b => lane_eqb (mulmx a b) (mulband (band a) (band b))) rk) rk = true.
Proof. vm_compute. reflexivity. Qed.
Theorem add_dispatch_commutes : forallb (fun a => forallb (fun b => lane_eqb (addmx a b) (addmx b a)) rk) rk = true.
Proof. vm_compute. reflexivity. Qed.
Theorem mul_dispatch_commutes : forallb (fun a => forallb (fun b => lane_eqb (mulmx a b) (mulmx b a)) rk) rk = true.
Proof. vm_compute. reflexivity. Qed.

(* the lattice, read off the diagonal: one add/mul lane pair per band *)
Theorem the_diagonal_reads_the_lattice :
  map (fun k => (addmx k k, mulmx k k)) [KMint; KNom; KCharm; KChain; KTablet]
  = [(Lbin_unit, Lbin_unit); (Ladd_string, L0); (Laddn, Lmuln); (Ladd_seq, Lmul_cart); (Laddh, Lmulh)].
Proof. vm_compute. reflexivity. Qed.

Print Assumptions add_factors_through_bands.   (* must stay "Closed under the global context" *)
Print Assumptions mul_dispatch_commutes.
